apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: faika/service_user:latest
        ports:
        - containerPort: 3005
        env:
        - name: MYSQL_HOST
          value: mysql-service.events.svc.cluster.local
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "pfe1"
